### ISSUE TITLE
miscount for avaialble entities

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_alchemist#18]
Three in this table, but says 4.

Probably not a miscount so much as a "bad" analysis in there....

![Screen Shot 2018-01-25 at 9.35.07 AM](http://static.gitscout.com/039e85ed8c7d7fa12a6da27b0f235ace4c724d74b1e55e3d82871c80eb187c8c.png)

**Comment by almasaeed2010** [comment]
It's possible that the count SQL isn't excluding the duplicates

**Comment by bradfordcondon** [comment]
unit test added in #55
