### ISSUE TITLE
changing div1 dropdowns leaves div2 output up

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_alchemist#22]
<img width="1174" alt="screen shot 2018-01-31 at 2 41 27 pm" src="https://user-images.githubusercontent.com/7063154/35643610-d9f7a5f4-0694-11e8-9f5f-6189820284ad.png">

IN this scenario there should be no table because no source bundle is given...

**Comment by jwest60** [comment]
[fixed on this branch](https://github.com/statonlab/tripal_alchemist/tree/fix-dropdowns)

div2 no longer exists and everything is done in div1 now. according to abdullah, this was the only way to actually fix this
