### ISSUE TITLE
collections picker dropdown display is ugly

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_alchemist#24]
Fix collections picker display

<img width="463" alt="screen shot 2018-01-31 at 4 04 20 pm" src="https://user-images.githubusercontent.com/7063154/35647424-7de102d6-06a0-11e8-86a3-d99e70bf2bc8.png">

**Comment by jwest60** [comment]
[fixed on this branch](https://github.com/statonlab/tripal_alchemist/tree/fix-picker)

**Comment by jwest60** [comment]
[fixed on this branch](https://github.com/statonlab/tripal_alchemist/tree/fix-picker)

**Comment by bradfordcondon** [comment]
thanks!
